# Generated by Django 4.2.11 on 2024-04-19 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_products_asin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='asin',
        ),
    ]
