# Generated by Django 4.2.11 on 2024-04-21 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_reviews_asin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='product',
            new_name='asin',
        ),
    ]
