# Generated by Django 4.2.11 on 2024-04-21 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_product_reviews_asin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
